# Generated by Django 5.2.6 on 2026-05-01 21:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('plan', models.CharField(choices=[('free', 'Grátis'), ('premium', 'Premium'), ('professional', 'Profissional'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Plano')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluída em')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'db_table': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx'), models.Index(fields=['plan'], name='organizatio_plan_b94df1_idx'), models.Index(fields=['deleted_at'], name='organizatio_deleted_0c15ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID público')),
                ('role', models.CharField(choices=[('PATIENT', 'Paciente'), ('DOCTOR', 'Médico(a)'), ('NURSE', 'Enfermeiro(a)'), ('NUTRITIONIST', 'Nutricionista'), ('PHYSIO', 'Fisioterapeuta'), ('SPEECH_THERAPIST', 'Fonoaudiólogo(a)'), ('PHYSICAL_EDUCATOR', 'Educador(a) Físico(a)'), ('PSYCHOLOGIST', 'Psicólogo(a)'), ('DENTIST', 'Dentista'), ('OCC_THERAPIST', 'Terapeuta Ocupacional'), ('PHARMACIST', 'Farmacêutico(a)'), ('BIOMEDICO', 'Biomédico(a)'), ('ADMIN', 'Administrador')], default='PATIENT', max_length=20, verbose_name='Perfil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Sobre mim')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profissão')),
                ('professional_specialty', models.CharField(blank=True, max_length=50, verbose_name='Especialidade')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='E-mail verificado')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Celular verificado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='users.organization', verbose_name='Organização')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('member', 'Membro'), ('viewer', 'Visualizador')], default='member', max_length=10, verbose_name='Papel')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro da Organização',
                'verbose_name_plural': 'Membros da Organização',
                'db_table': 'organization_members',
            },
        ),
        migrations.CreateModel(
            name='PatientProfessionalAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo do acesso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Concedido em')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revogado em')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Concedido por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Vínculo Paciente-Profissional',
                'verbose_name_plural': 'Vínculos Paciente-Profissional',
                'db_table': 'patient_professional_accesses',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('', 'Não informado')], max_length=3, verbose_name='Tipo sanguíneo')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='Condições crônicas')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('current_medications', models.TextField(blank=True, verbose_name='Medicamentos em uso')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contato de emergência')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de emergência')),
                ('health_insurance', models.CharField(blank=True, max_length=100, verbose_name='Plano de saúde')),
                ('health_insurance_number', models.CharField(blank=True, max_length=50, verbose_name='Número do plano')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=10, verbose_name='Nível de risco')),
                ('ai_last_analysis', models.DateTimeField(blank=True, null=True, verbose_name='Última análise IA')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Resumo gerado por IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil do Paciente',
                'verbose_name_plural': 'Perfis dos Pacientes',
                'db_table': 'patient_profiles',
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('email', 'Verificação de e-mail'), ('phone', 'Verificação de celular'), ('login', 'Login por código'), ('reset', 'Redefinição de senha')], default='email', max_length=10)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Verificação',
                'verbose_name_plural': 'Códigos de Verificação',
                'db_table': 'verification_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'Visualização'), ('create', 'Criação'), ('edit', 'Edição'), ('delete', 'Exclusão'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Exportação'), ('access_denied', 'Acesso negado')], max_length=20, verbose_name='Ação')),
                ('resource_type', models.CharField(max_length=50, verbose_name='Tipo de recurso')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='ID do recurso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('success', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Momento')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Ator')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_patient', to=settings.AUTH_USER_MODEL, verbose_name='Paciente envolvido')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', 'timestamp'], name='audit_logs_actor_i_ce2144_idx'), models.Index(fields=['patient', 'timestamp'], name='audit_logs_patient_5d0372_idx'), models.Index(fields=['resource_type', 'timestamp'], name='audit_logs_resourc_4f6f11_idx'), models.Index(fields=['action', 'success'], name='audit_logs_action_47eca6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['uid'], name='users_uid_f6e4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['deleted_at'], name='users_deleted_e48316_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_4b82c6_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['user', 'is_active'], name='organizatio_user_id_fac103_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'user')},
        ),
        migrations.AddIndex(
            model_name='patientprofessionalaccess',
            index=models.Index(fields=['patient', 'is_active'], name='patient_pro_patient_dce09c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofessionalaccess',
            index=models.Index(fields=['professional', 'is_active'], name='patient_pro_profess_bdbf15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientprofessionalaccess',
            unique_together={('patient', 'professional')},
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['cpf'], name='patient_pro_cpf_ae47df_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['risk_level'], name='patient_pro_risk_le_e54fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['blood_type'], name='patient_pro_blood_t_c3c270_idx'),
        ),
    ]
