# Generated by Django 5.2.11 on 2026-06-12 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_platform_feedback'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='platformfeedback',
            new_name='platform_fe_created_05758b_idx',
            old_name='feedback_created_idx',
        ),
        migrations.RenameIndex(
            model_name='platformfeedback',
            new_name='platform_fe_role_at_8d0bee_idx',
            old_name='feedback_role_idx',
        ),
        migrations.AlterField(
            model_name='platformfeedback',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
