# Generated by Django 5.2.11 on 2026-06-24 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0003_rename_feedback_created_idx_platform_fe_created_05758b_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Grátis"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="Plano",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Válido até"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans_granted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Concedido por",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_plan",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Usuário",
                "verbose_name_plural": "Planos de Usuário",
                "db_table": "user_plans",
            },
        ),
    ]
