# Generated by Django 5.2.12 on 2026-03-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profissão'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='professional_specialty',
            field=models.CharField(blank=True, max_length=50, verbose_name='Especialidade'),
        ),
    ]
