# Generated by Django 5.2.11 on 2026-04-21 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_uid(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all():
        user.uid = uuid.uuid4()
        user.save(update_fields=['uid'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_customuser_profession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('member', 'Membro'), ('viewer', 'Visualizador')], default='member', max_length=10, verbose_name='Papel')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membro da Organização',
                'verbose_name_plural': 'Membros da Organização',
                'db_table': 'organization_members',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('', 'Não informado')], max_length=3, verbose_name='Tipo sanguíneo')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='Condições crônicas')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('current_medications', models.TextField(blank=True, verbose_name='Medicamentos em uso')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contato de emergência')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de emergência')),
                ('health_insurance', models.CharField(blank=True, max_length=100, verbose_name='Plano de saúde')),
                ('health_insurance_number', models.CharField(blank=True, max_length=50, verbose_name='Número do plano')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=10, verbose_name='Nível de risco')),
                ('ai_last_analysis', models.DateTimeField(blank=True, null=True, verbose_name='Última análise IA')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Resumo gerado por IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil do Paciente',
                'verbose_name_plural': 'Perfis dos Pacientes',
                'db_table': 'patient_profiles',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluído em'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False, verbose_name='UUID público'),
        ),
        migrations.RunPython(populate_uid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID público'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Paciente'), ('DOCTOR', 'Médico'), ('NURSE', 'Enfermeiro'), ('NUTRITIONIST', 'Nutricionista'), ('PHYSIO', 'Fisioterapeuta'), ('ADMIN', 'Administrador')], default='PATIENT', max_length=20, verbose_name='Perfil'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='verificationcode',
            table='verification_codes',
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('plan', models.CharField(choices=[('free', 'Grátis'), ('premium', 'Premium'), ('professional', 'Profissional'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Plano')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluída em')),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'db_table': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx'), models.Index(fields=['plan'], name='organizatio_plan_b94df1_idx'), models.Index(fields=['deleted_at'], name='organizatio_deleted_0c15ba_idx')],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='users.organization', verbose_name='Organização'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['uid'], name='users_uid_f6e4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['deleted_at'], name='users_deleted_e48316_idx'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.organization'),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_4b82c6_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['user', 'is_active'], name='organizatio_user_id_fac103_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together={('organization', 'user')},
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['cpf'], name='patient_pro_cpf_ae47df_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['risk_level'], name='patient_pro_risk_le_e54fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['blood_type'], name='patient_pro_blood_t_c3c270_idx'),
        ),
    ]
