# Generated by Django 5.2.11 on 2026-08-27 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_index_is_email_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalPatient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome completo"),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, verbose_name="CPF"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de nascimento"
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Observações clínicas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paciente Externo",
                "verbose_name_plural": "Pacientes Externos",
                "db_table": "external_patients",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="customuser",
            name="users_email_verified_idx",
        ),
        migrations.AddField(
            model_name="externalpatient",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="external_patients_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cadastrado por",
            ),
        ),
        migrations.AddField(
            model_name="externalpatient",
            name="linked_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_patient_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Conta LIDDIS vinculada",
            ),
        ),
        migrations.AddIndex(
            model_name="externalpatient",
            index=models.Index(
                fields=["created_by"], name="external_pa_created_fc3277_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalpatient",
            index=models.Index(fields=["cpf"], name="external_pa_cpf_afc03e_idx"),
        ),
    ]
