# Generated by Django 5.2.11 on 2026-09-15 19:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("professional", "Termos do Profissional"),
                            ("patient", "Termos do Paciente"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "versao",
                    models.CharField(
                        help_text="Ex.: 1.0. Toda alteração de cláusula exige versão nova.",
                        max_length=20,
                        verbose_name="Versão",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "template",
                    models.CharField(
                        help_text="Caminho do template com o texto, ex.: legal/professional_v1_0.html",
                        max_length=200,
                        verbose_name="Template",
                    ),
                ),
                ("vigente_desde", models.DateField(verbose_name="Vigente desde")),
                (
                    "exige_novo_aceite",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarque em correções de forma que não alterem direitos e deveres.",
                        verbose_name="Exige novo aceite",
                    ),
                ),
                (
                    "publicado",
                    models.BooleanField(default=True, verbose_name="Publicado"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Documento jurídico",
                "verbose_name_plural": "Documentos jurídicos",
                "db_table": "legal_terms_document",
                "ordering": ["tipo", "-vigente_desde", "-versao"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tipo", "versao"), name="documento_versao_unica"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TermsAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(max_length=20, verbose_name="Tipo"),
                ),
                (
                    "versao",
                    models.CharField(max_length=20, verbose_name="Versão aceita"),
                ),
                (
                    "papel",
                    models.CharField(
                        help_text="PATIENT, DOCTOR, NURSE etc. no momento do aceite.",
                        max_length=20,
                        verbose_name="Papel na época",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("signup", "Cadastro"),
                            ("reaccept", "Novo aceite de versão"),
                            ("oauth", "Cadastro via Google"),
                        ],
                        default="signup",
                        max_length=20,
                        verbose_name="Origem do aceite",
                    ),
                ),
                (
                    "aceito_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data e hora"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Navegador"
                    ),
                ),
                (
                    "declarou_habilitacao",
                    models.BooleanField(
                        default=False, verbose_name="Declarou habilitação profissional"
                    ),
                ),
                (
                    "aceitou_marketing",
                    models.BooleanField(
                        default=False, verbose_name="Aceitou comunicações de marketing"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aceites_termos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aceites",
                        to="legal.termsdocument",
                        verbose_name="Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aceite de termos",
                "verbose_name_plural": "Aceites de termos",
                "db_table": "legal_terms_acceptance",
                "ordering": ["-aceito_em"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "tipo_documento"],
                        name="aceite_usuario_tipo_idx",
                    )
                ],
            },
        ),
    ]
