# Generated by Django 5.2.12 on 2026-03-17 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da consulta')),
                ('professional_name', models.CharField(max_length=150, verbose_name='Nome do profissional')),
                ('specialty', models.CharField(choices=[('clinico_geral', 'Clínico Geral'), ('cardiologia', 'Cardiologia'), ('neurologia', 'Neurologia'), ('ortopedia', 'Ortopedia'), ('nutricao', 'Nutrição'), ('fisioterapia', 'Fisioterapia'), ('enfermagem', 'Enfermagem'), ('psicologia', 'Psicologia'), ('dermatologia', 'Dermatologia'), ('ginecologia', 'Ginecologia'), ('pediatria', 'Pediatria'), ('outro', 'Outro')], max_length=50, verbose_name='Especialidade')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações / Evolução')),
                ('prescription', models.TextField(blank=True, verbose_name='Prescrição / Medicamentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da medição')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, verbose_name='Pressão arterial (ex: 120/80)')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequência cardíaca (bpm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Saturação O₂ (%)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinal Vital',
                'verbose_name_plural': 'Sinais Vitais',
                'ordering': ['-date'],
            },
        ),
    ]
