# Generated by Django 5.2.6 on 2026-05-01 21:49

import consultations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='Queixa principal')),
                ('history', models.TextField(blank=True, verbose_name='História da doença atual')),
                ('past_history', models.TextField(blank=True, verbose_name='Antecedentes pessoais')),
                ('family_history', models.TextField(blank=True, verbose_name='Antecedentes familiares')),
                ('medications', models.TextField(blank=True, verbose_name='Medicamentos em uso')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
                'db_table': 'anamneses',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Data da consulta')),
                ('professional_name', models.CharField(max_length=150, verbose_name='Nome do profissional')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profissão do profissional')),
                ('clinic_name', models.CharField(blank=True, max_length=200, verbose_name='Nome do local')),
                ('clinic_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('clinic_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('clinic_address', models.CharField(blank=True, max_length=300, verbose_name='Endereço completo')),
                ('specialty', models.CharField(choices=[('clinico_geral', 'Clínico Geral'), ('cardiologia', 'Cardiologia'), ('neurologia', 'Neurologia'), ('ortopedia', 'Ortopedia'), ('nutricao', 'Nutrição'), ('fisioterapia', 'Fisioterapia'), ('enfermagem', 'Enfermagem'), ('psicologia', 'Psicologia'), ('dermatologia', 'Dermatologia'), ('ginecologia', 'Ginecologia'), ('pediatria', 'Pediatria'), ('outro', 'Outro')], max_length=50, verbose_name='Especialidade')),
                ('specialty_other', models.CharField(blank=True, max_length=100, verbose_name='Especialidade (Outro)')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações / Evolução')),
                ('prescription', models.TextField(blank=True, verbose_name='Prescrição / Medicamentos')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='active', max_length=10, verbose_name='Status')),
                ('severity', models.CharField(blank=True, choices=[('low', 'Leve'), ('moderate', 'Moderada'), ('high', 'Grave'), ('critical', 'Crítica')], max_length=10, verbose_name='Gravidade')),
                ('icd_code', models.CharField(blank=True, max_length=10, verbose_name='CID-10')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Resumo gerado por IA')),
                ('ai_last_analysis', models.DateTimeField(blank=True, null=True, verbose_name='Última análise IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'consultations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(choices=[('anamnese', 'Anamnese'), ('exames', 'Exames Laboratoriais'), ('diagnostico', 'Diagnóstico'), ('prescricao', 'Prescrição')], max_length=20, verbose_name='Aba')),
                ('image', models.ImageField(upload_to=consultations.models.consultation_image_path, verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Legenda')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem da Consulta',
                'verbose_name_plural': 'Imagens das Consultas',
                'db_table': 'consultation_images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Aguardando profissional'), ('active', 'Em atendimento'), ('closed', 'Encerrado'), ('expired', 'Expirado')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sessão de Atendimento',
                'verbose_name_plural': 'Sessões de Atendimento',
                'db_table': 'consultation_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisCID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icd_code', models.CharField(max_length=10, verbose_name='Código CID-10')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
                ('notes', models.TextField(blank=True, verbose_name='Observações clínicas')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Diagnóstico principal')),
                ('certainty', models.CharField(choices=[('confirmed', 'Confirmado'), ('presumed', 'Presumido'), ('ruled_out', 'Descartado')], default='confirmed', max_length=10, verbose_name='Certeza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Diagnóstico CID',
                'verbose_name_plural': 'Diagnósticos CID',
                'db_table': 'diagnoses_cid',
                'ordering': ['-created_at', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('medical', 'Médica'), ('nursing', 'Enfermagem'), ('physio', 'Fisioterapia'), ('nutrition', 'Nutrição'), ('speech', 'Fonoaudiologia'), ('psychology', 'Psicologia'), ('occupational', 'Terapia Ocupacional'), ('dental', 'Odontologia'), ('pharmacy', 'Farmácia'), ('physical_ed', 'Educação Física'), ('other', 'Outro')], max_length=20, verbose_name='Categoria')),
                ('content', models.TextField(verbose_name='Conteúdo da evolução')),
                ('is_visible_to_patient', models.BooleanField(default=True, verbose_name='Visível ao paciente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evolução',
                'verbose_name_plural': 'Evoluções',
                'db_table': 'evolutions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExameLaboratorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemograma', models.TextField(blank=True, verbose_name='Hemograma')),
                ('glicemia', models.TextField(blank=True, verbose_name='Glicemia')),
                ('colesterol', models.TextField(blank=True, verbose_name='Colesterol e triglicerídeos')),
                ('funcao_renal', models.TextField(blank=True, verbose_name='Função renal (creatinina, ureia)')),
                ('funcao_hepatica', models.TextField(blank=True, verbose_name='Função hepática')),
                ('hormonal', models.TextField(blank=True, verbose_name='Exames hormonais')),
                ('urina', models.TextField(blank=True, verbose_name='Urina (EAS)')),
                ('outros', models.TextField(blank=True, verbose_name='Outros exames')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exame Laboratorial',
                'verbose_name_plural': 'Exames Laboratoriais',
                'db_table': 'exames_laboratoriais',
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(max_length=100, verbose_name='Tipo de exame')),
                ('exam_description', models.TextField(blank=True, verbose_name='Descrição / parâmetros')),
                ('urgency', models.BooleanField(default=False, verbose_name='Urgência')),
                ('result', models.TextField(blank=True, verbose_name='Resultado')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='Data do resultado')),
                ('reference_values', models.TextField(blank=True, verbose_name='Valores de referência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('collected', 'Coletado'), ('completed', 'Resultado disponível'), ('cancelled', 'Cancelado')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitação de Exame',
                'verbose_name_plural': 'Solicitações de Exame',
                'db_table': 'lab_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('general_state', models.TextField(blank=True, verbose_name='Estado geral')),
                ('cardiovascular', models.TextField(blank=True, verbose_name='Cardiovascular')),
                ('respiratory', models.TextField(blank=True, verbose_name='Respiratório')),
                ('abdomen', models.TextField(blank=True, verbose_name='Abdome')),
                ('neurological', models.TextField(blank=True, verbose_name='Neurológico')),
                ('musculoskeletal', models.TextField(blank=True, verbose_name='Musculoesquelético')),
                ('skin', models.TextField(blank=True, verbose_name='Pele e mucosas')),
                ('orl', models.TextField(blank=True, verbose_name='ORL / Cabeça e pescoço')),
                ('other_systems', models.TextField(blank=True, verbose_name='Outros sistemas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exame Físico',
                'verbose_name_plural': 'Exames Físicos',
                'db_table': 'physical_exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_type', models.CharField(choices=[('medical', 'Médica'), ('nursing', 'Enfermagem'), ('dental', 'Odontológica'), ('dietary', 'Dietética'), ('pharmacy', 'Farmacêutica')], max_length=10, verbose_name='Tipo')),
                ('medication_name', models.CharField(blank=True, max_length=200, verbose_name='Medicamento / Item')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='Dose')),
                ('frequency', models.CharField(blank=True, max_length=100, verbose_name='Frequência')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Duração')),
                ('route', models.CharField(blank=True, max_length=50, verbose_name='Via de administração')),
                ('content', models.TextField(blank=True, verbose_name='Prescrição completa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescrição',
                'verbose_name_plural': 'Prescrições',
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data da medição')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, verbose_name='Pressão arterial (ex: 120/80)')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frequência cardíaca (bpm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Saturação O₂ (%)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sinal Vital',
                'verbose_name_plural': 'Sinais Vitais',
                'db_table': 'vital_signs',
                'ordering': ['-date'],
            },
        ),
    ]
