# Generated by Django 5.2.6 on 2026-05-01 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='users.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='consultationimage',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='consultationsession',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='consultationsession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationsession',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosiscid',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='diagnosiscid',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_written', to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='evolution',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='evolution',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions_written', to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='examelaboratorial',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='requesting_professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='result_registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_entered', to=settings.AUTH_USER_MODEL, verbose_name='Quem registrou o resultado'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_exams', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='physicalexam',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_exams_written', to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL, verbose_name='Prescritor'),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', 'date'], name='consultatio_patient_3f58e7_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['organization'], name='consultatio_organiz_5d7a35_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status'], name='consultatio_status_beb187_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['severity'], name='consultatio_severit_28f93d_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['icd_code'], name='consultatio_icd_cod_fe79ba_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosiscid',
            index=models.Index(fields=['consultation'], name='diagnoses_c_consult_0c3251_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosiscid',
            index=models.Index(fields=['icd_code'], name='diagnoses_c_icd_cod_dac97e_idx'),
        ),
        migrations.AddIndex(
            model_name='evolution',
            index=models.Index(fields=['consultation', 'category'], name='evolutions_consult_71b6c4_idx'),
        ),
        migrations.AddIndex(
            model_name='evolution',
            index=models.Index(fields=['professional'], name='evolutions_profess_121cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['consultation', 'status'], name='lab_request_consult_841477_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['requesting_professional'], name='lab_request_request_d3bdc4_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['status'], name='lab_request_status_652ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['consultation', 'is_active'], name='prescriptio_consult_5a4749_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescriber'], name='prescriptio_prescri_6083a3_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_type'], name='prescriptio_prescri_9650be_idx'),
        ),
    ]
