# Generated by Django 5.2.12 on 2026-03-22 22:22

import consultations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='specialty_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Especialidade (Outro)'),
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='Queixa principal')),
                ('history', models.TextField(blank=True, verbose_name='História da doença atual')),
                ('past_history', models.TextField(blank=True, verbose_name='Antecedentes pessoais')),
                ('family_history', models.TextField(blank=True, verbose_name='Antecedentes familiares')),
                ('medications', models.TextField(blank=True, verbose_name='Medicamentos em uso')),
                ('allergies', models.TextField(blank=True, verbose_name='Alergias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
            },
        ),
        migrations.CreateModel(
            name='ConsultationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(choices=[('anamnese', 'Anamnese'), ('exames', 'Exames Laboratoriais'), ('diagnostico', 'Diagnóstico'), ('prescricao', 'Prescrição')], max_length=20, verbose_name='Aba')),
                ('image', models.ImageField(upload_to=consultations.models.consultation_image_path, verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Legenda')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Imagem da Consulta',
                'verbose_name_plural': 'Imagens das Consultas',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExameLaboratorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemograma', models.TextField(blank=True, verbose_name='Hemograma')),
                ('glicemia', models.TextField(blank=True, verbose_name='Glicemia')),
                ('colesterol', models.TextField(blank=True, verbose_name='Colesterol e triglicerídeos')),
                ('funcao_renal', models.TextField(blank=True, verbose_name='Função renal (creatinina, ureia)')),
                ('funcao_hepatica', models.TextField(blank=True, verbose_name='Função hepática')),
                ('hormonal', models.TextField(blank=True, verbose_name='Exames hormonais')),
                ('urina', models.TextField(blank=True, verbose_name='Urina (EAS)')),
                ('outros', models.TextField(blank=True, verbose_name='Outros exames')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Exame Laboratorial',
                'verbose_name_plural': 'Exames Laboratoriais',
            },
        ),
    ]
