# Generated by Django 5.2.12 on 2026-03-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultation_specialty_other_anamnese_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço do local'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do local'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='profession',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profissão do profissional'),
        ),
    ]
