# Generated by Django 5.2.12 on 2026-03-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_consultation_clinic_address_consultation_clinic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='clinic_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='clinic_neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço completo'),
        ),
    ]
