# Generated by Django 5.2.11 on 2026-04-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_clinic_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ai_last_analysis',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última análise IA'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ai_summary',
            field=models.TextField(blank=True, verbose_name='Resumo gerado por IA'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='icd_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='CID-10'),
        ),
    ]
