# Generated by Django 5.2.11 on 2026-04-21 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_consultation_ai_last_analysis_and_more'),
        ('users', '0005_organizationmember_patientprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='users.organization', verbose_name='Organização'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Leve'), ('moderate', 'Moderada'), ('high', 'Grave'), ('critical', 'Crítica')], max_length=10, verbose_name='Gravidade'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', 'date'], name='consultatio_patient_3f58e7_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['organization'], name='consultatio_organiz_5d7a35_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status'], name='consultatio_status_beb187_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['severity'], name='consultatio_severit_28f93d_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['icd_code'], name='consultatio_icd_cod_fe79ba_idx'),
        ),
        migrations.AlterModelTable(
            name='anamnese',
            table='anamneses',
        ),
        migrations.AlterModelTable(
            name='consultation',
            table='consultations',
        ),
        migrations.AlterModelTable(
            name='consultationimage',
            table='consultation_images',
        ),
        migrations.AlterModelTable(
            name='consultationsession',
            table='consultation_sessions',
        ),
        migrations.AlterModelTable(
            name='examelaboratorial',
            table='exames_laboratoriais',
        ),
        migrations.AlterModelTable(
            name='vitalsign',
            table='vital_signs',
        ),
    ]
