# Generated by Django 5.2.11 on 2026-05-29 02:17

import consultations.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_vitalsign_other_signs_remove_expectedevolution_prognosis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Anexo da Consulta', 'verbose_name_plural': 'Anexos das Consultas'},
        ),
        migrations.RenameIndex(
            model_name='vitalsign',
            new_name='vital_signs_patient_6feb97_idx',
            old_name='vitals_patient_date_idx',
        ),
        migrations.RenameIndex(
            model_name='vitalsign',
            new_name='vital_signs_consult_f11d1e_idx',
            old_name='vitals_consultation_idx',
        ),
        migrations.AlterField(
            model_name='clinicalintervention',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consultationimage',
            name='image',
            field=models.FileField(upload_to=consultations.models.consultation_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf'])], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='expectedevolution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patientclinicalsummary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
