# Generated by Django 5.2.11 on 2026-06-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_consultationimage_filefield_pdf_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='record_origin',
            field=models.CharField(choices=[('platform', 'Consulta realizada na plataforma'), ('patient_manual', 'Consulta cadastrada pelo paciente')], db_index=True, default='platform', max_length=20, verbose_name='Origem do Registro'),
        ),
    ]
