# Generated by Django 5.2.11 on 2026-07-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0009_consultation_record_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientclinicalsummary",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Peso de referência (kg)",
            ),
        ),
    ]
