# Generated by Django 5.2.11 on 2026-08-27 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0011_remove_classification_code_add_consultation_creator"),
        ("users", "0006_external_patient_and_nullable_consultation_patient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="external_patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultations",
                to="users.externalpatient",
                verbose_name="Paciente externo",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="external_patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vitals",
                to="users.externalpatient",
                verbose_name="Paciente externo",
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Paciente",
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="record_origin",
            field=models.CharField(
                choices=[
                    ("platform", "Consulta realizada na plataforma"),
                    ("patient_manual", "Consulta cadastrada pelo paciente"),
                    ("external", "Paciente sem conta LIDDIS"),
                ],
                db_index=True,
                default="platform",
                max_length=20,
                verbose_name="Origem do Registro",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vitals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
