# Generated by Django 5.2.11 on 2026-09-11 01:53

import consultations.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0012_external_patient_and_nullable_consultation_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationimage",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to=consultations.models.consultation_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "pdf"]
                    )
                ],
                verbose_name="Arquivo",
            ),
        ),
    ]
